sulu_media:
    system_collections:
        travel_plan_documents:
            meta_title:
                nl: Reisplannen
                en: Travel plans
        travel_memory_albums:
            meta_title:
                nl: Reisherinneringsalbums
                en: Travel memory albums
