sulu_admin:
    email: "%env(SULU_ADMIN_EMAIL)%"
    resources:
        travel_requests:
            routes:
                list: travel_request.get_collection
                detail: travel_request.get
            security_context: jouwreiswijzer.travel_requests
        travel_request_plans:
            routes:
                detail: travel_request_plan.get
            security_context: jouwreiswijzer.travel_requests
        push_rules:
            routes:
                list: push_rules.get_collection
                detail: push_rules.get
            security_context: jouwreiswijzer.push_rules
        manual_push_messages:
            routes:
                list: manual_push_messages.get_collection
                detail: manual_push_messages.get
            security_context: jouwreiswijzer.push_rules
    icon_sets:
        decor: "svg://%kernel.project_dir%/assets/images/icons"
        travel_plan_icons: "svg://%kernel.project_dir%/assets/images/icons"
    forms:
        directories:
            - "%kernel.project_dir%/config/forms"
    lists:
        directories:
            - "%kernel.project_dir%/config/lists"
